
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA COMA ELSE FOR IF IGUAL INT LLAVEDER LLAVEIZQ MAS MASMAS MAYORIGUAL MENORIGUAL NUMERO OUT PARDER PARIZQ PRINTLN PUNTO PUNTOYCOMA SYSTEM WHILE identificadorinstruccion : FOR PARIZQ INT identificador IGUAL NUMERO PUNTOYCOMA identificador MENORIGUAL NUMERO PUNTOYCOMA identificador MASMAS PARDER bloquebloque : LLAVEIZQ instruccion_llamada LLAVEDERinstruccion_llamada : SYSTEM PUNTO OUT PUNTO PRINTLN PARIZQ CADENA MAS identificador PARDER PUNTOYCOMA'
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,16,20,],[0,-1,-2,]),'PARIZQ':([2,24,],[3,25,]),'INT':([3,],[4,]),'identificador':([4,8,12,27,],[5,9,13,28,]),'IGUAL':([5,],[6,]),'NUMERO':([6,10,],[7,11,]),'PUNTOYCOMA':([7,11,29,],[8,12,30,]),'MENORIGUAL':([9,],[10,]),'MASMAS':([13,],[14,]),'PARDER':([14,28,],[15,29,]),'LLAVEIZQ':([15,],[17,]),'SYSTEM':([17,],[19,]),'LLAVEDER':([18,30,],[20,-3,]),'PUNTO':([19,22,],[21,23,]),'OUT':([21,],[22,]),'PRINTLN':([23,],[24,]),'CADENA':([25,],[26,]),'MAS':([26,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instruccion':([0,],[1,]),'bloque':([15,],[16,]),'instruccion_llamada':([17,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instruccion","S'",1,None,None,None),
  ('instruccion -> FOR PARIZQ INT identificador IGUAL NUMERO PUNTOYCOMA identificador MENORIGUAL NUMERO PUNTOYCOMA identificador MASMAS PARDER bloque','instruccion',15,'p_instruccion_for','analizador_lexico.py',75),
  ('bloque -> LLAVEIZQ instruccion_llamada LLAVEDER','bloque',3,'p_bloque','analizador_lexico.py',80),
  ('instruccion_llamada -> SYSTEM PUNTO OUT PUNTO PRINTLN PARIZQ CADENA MAS identificador PARDER PUNTOYCOMA','instruccion_llamada',11,'p_instruccion_llamada','analizador_lexico.py',85),
]
